dadas

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -19,8 +19,6 @@ jobs:
   build:
     name: "Build Project"
     runs-on: ubuntu-latest
-    needs: lint
-
     steps:
       # Checkout the latest commit of the branch
       - name: Checkout Code to Latest Commit of Branch ${{ github.event.inputs.branch }}
@@ -113,6 +111,7 @@ jobs:
   lint:
     name: "Run Lint Checks"
     runs-on: ubuntu-latest
+    needs: build
 
     steps:
       # Checkout the latest commit of the branch
@@ -201,7 +200,7 @@ jobs:
   debug-apk:
     name: Generate and Upload Debug APK
     runs-on: ubuntu-latest
-    needs: build
+    needs: instrumentation-tests
 
     steps:
       # Checkout the latest commit of the branch
@@ -281,7 +280,7 @@ jobs:
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with: 
-          name: "Agent-App-${{ env.commit_hash }}"
+          name: "Kommunicate-SDK-${{ env.commit_hash }}"
           path: app/build/outputs/apk/debug/app-debug.apk
  
       # Retrieve Artifact URL
@@ -323,7 +322,7 @@ jobs:
   comment-on-pr:
     name: "Post CodeRabbit Review Request"
     needs: build
-    runs-on: ubuntu-latest
+    runs-on: instrumentation-tests
 
     steps:
       # Checkout the repository (optional, if code is needed)
@@ -341,3 +340,98 @@ jobs:
               issue_number: context.payload.pull_request.number,
               body: "@coderabbit review"
             });
+  
+  instrumentation-tests:
+    name: Run Instrumentation Tests
+    runs-on: ubuntu-latest
+    needs: lint
+    strategy:
+      matrix:
+        api-level: [ 30 ]
+        target: [ google_apis ]
+
+    steps:
+      # Checkout the code
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # Enable KVM for faster test execution
+      - name: Enable KVM group perms
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+
+      # Setup or Load the cached gradle
+      - name: Gradle cache
+        uses: gradle/actions/setup-gradle@v3
+
+      # Load the AVD Cache. For android emulator
+      - name: AVD cache
+        uses: actions/cache@v4
+        id: avd-cache
+        with:
+          path: |
+            ~/.android/avd/*
+            ~/.android/adb*
+          key: avd-${{ matrix.api-level }}
+
+      # Setup the AVD if not cached
+      - name: create AVD and generate snapshot for caching
+        if: steps.avd-cache.outputs.cache-hit != 'true'
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: ${{ matrix.api-level }}
+          target: ${{ matrix.target }}
+          emulator-port: 5582
+          force-avd-creation: false
+          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: echo "Generated AVD snapshot for caching."
+
+      # Create local.properties
+      - name: Create local.properties
+        run: |
+          echo "sdk.dir=$ANDROID_HOME" > local.properties
+          echo "GOOGLE_KEY=${{ secrets.GOOGLE_MAPS_API }}" >> local.properties
+
+      # Create release.secrets.properties
+      - name: Create release.secrets.properties
+        run: |
+          echo "apiKommunicateIo=${{ secrets.APIKOMMUNICATEIO }}" >> release.secrets.properties
+          echo "apiEuKommunicateIo=${{ secrets.APIEUKOMMUNICATEIO }}" >> release.secrets.properties
+          echo "apiCaKommunicateIo=${{ secrets.APICAKOMMUNICATEIO }}" >> release.secrets.properties
+          echo "apiTestKommuncateIo=${{ secrets.APITESTKOMMUNCATEIO }}" >> release.secrets.properties
+          echo "kommunicateIo=${{ secrets.KOMMUNICATEIO }}" >> release.secrets.properties
+          echo "apiInKommunicateIo=${{ secrets.APIINKOMMUNICATEIO }}" >> release.secrets.properties
+          echo "kommunicateAWS=${{ secrets.KOMMUNICATEAWS }}" >> release.secrets.properties
+          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> release.secrets.properties
+          
+      - name: run tests
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: ${{ matrix.api-level }}
+          target: ${{ matrix.target }}
+          emulator-port: 5582
+          force-avd-creation: false
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: |
+            set -e
+            ./gradlew assembleDebug assembleAndroidTest
+            ./gradlew connectedAndroidTest || {
+              echo "Tests failed. Uploading results before exit."
+              exit 1
+            }
+          
+      # Upload Test Results
+      - name: Upload Test Results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: |
+            app/build/reports/androidTests/
+            app/build/reports/androidTests/connected/
+            app/build/outputs/androidTest-results/
+          retention-days: 14
